/**
 * Analyze check-in trends and progress
 */

export const getCheckinHistory = () => {
  try {
    const checkins = JSON.parse(localStorage.getItem('checkins') || '[]')
    return checkins.sort((a, b) => new Date(a.date) - new Date(b.date))
  } catch (error) {
    console.error('Error reading check-ins:', error)
    return []
  }
}

/**
 * Generate mock check-in data if none exists (for demo)
 */
export const generateMockCheckins = (days = 30) => {
  const checkins = []
  const today = new Date()
  
  for (let i = days; i >= 0; i--) {
    const date = new Date(today)
    date.setDate(date.getDate() - i)
    
    // Simulate improving trends - start at 2-3, decrease to 0-1
    // i goes from days (oldest) to 0 (newest), so progressFactor = 1 (oldest) to 0 (newest)
    const progressFactor = i / days // 1 = oldest, 0 = newest
    
    // Start with higher values (2-3) at oldest and decrease to lower values (0-1) at newest
    const baseValue = 2 + Math.floor(Math.random() * 2) // 2-3 for older dates
    const improvedValue = Math.floor(Math.random() * 2) // 0-1 for newer dates
    const breakout = progressFactor > 0.7 ? baseValue : improvedValue
    
    const baseIrritation = 2 + Math.floor(Math.random() * 2)
    const improvedIrritation = Math.floor(Math.random() * 2)
    const irritation = progressFactor > 0.6 ? baseIrritation : improvedIrritation
    
    const baseDryness = 2 + Math.floor(Math.random() * 2)
    const improvedDryness = Math.floor(Math.random() * 2)
    const dryness = progressFactor > 0.8 ? baseDryness : improvedDryness
    
    const baseRedness = 2 + Math.floor(Math.random() * 2)
    const improvedRedness = Math.floor(Math.random() * 2)
    const redness = progressFactor > 0.7 ? baseRedness : improvedRedness
    
    checkins.push({
      date: date.toISOString(),
      breakout,
      irritation,
      dryness,
      redness,
      triedSomethingNew: i % 7 === 0 // Every week
    })
  }
  
  return checkins
}

/**
 * Get check-in data for charts
 */
export const getCheckinChartData = () => {
  let checkins = getCheckinHistory()
  
  // If no check-ins, generate mock data for demo
  if (checkins.length === 0) {
    checkins = generateMockCheckins(30)
  }
  
  // Format for charts
  return checkins.map(checkin => ({
    date: new Date(checkin.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    fullDate: checkin.date,
    breakout: checkin.breakout || 0,
    irritation: checkin.irritation || 0,
    dryness: checkin.dryness || 0,
    redness: checkin.redness || 0,
    triedSomethingNew: checkin.triedSomethingNew || false
  }))
}

/**
 * Calculate trend analysis
 */
export const calculateTrends = (checkins) => {
  if (checkins.length < 2) {
    return {
      breakout: 'insufficient-data',
      irritation: 'insufficient-data',
      dryness: 'insufficient-data',
      redness: 'insufficient-data'
    }
  }

  const firstHalf = checkins.slice(0, Math.floor(checkins.length / 2))
  const secondHalf = checkins.slice(Math.floor(checkins.length / 2))

  const calculateAverage = (arr, field) => {
    const sum = arr.reduce((acc, item) => acc + (item[field] || 0), 0)
    return sum / arr.length
  }

  const getTrend = (field) => {
    const firstAvg = calculateAverage(firstHalf, field)
    const secondAvg = calculateAverage(secondHalf, field)
    const diff = secondAvg - firstAvg
    
    if (Math.abs(diff) < 0.1) return 'stable'
    if (diff < 0) return 'improving'
    return 'worsening'
  }

  return {
    breakout: getTrend('breakout'),
    irritation: getTrend('irritation'),
    dryness: getTrend('dryness'),
    redness: getTrend('redness')
  }
}

/**
 * Get overall progress summary
 */
export const getProgressSummary = (checkins) => {
  if (checkins.length === 0) {
    return {
      overallTrend: 'insufficient-data',
      mostImproved: null,
      daysSinceLastReaction: null,
      totalCheckins: 0
    }
  }

  const trends = calculateTrends(checkins)
  const improvingCount = Object.values(trends).filter(t => t === 'improving').length
  const worseningCount = Object.values(trends).filter(t => t === 'worsening').length

  let overallTrend = 'stable'
  if (improvingCount > worseningCount) {
    overallTrend = 'improving'
  } else if (worseningCount > improvingCount) {
    overallTrend = 'worsening'
  }

  // Find most improved concern
  const mostImproved = Object.entries(trends)
    .filter(([_, trend]) => trend === 'improving')
    .map(([concern, _]) => concern)[0] || null

  // Days since last negative reaction (score > 1)
  // Check if this is mock data (generated by generateMockCheckins)
  // Mock data will have dates that are recent (within last 30 days)
  const isMockData = checkins.length > 0 && checkins.some(c => {
    const checkinDate = new Date(c.date)
    const today = new Date()
    const daysDiff = Math.floor((today - checkinDate) / (1000 * 60 * 60 * 24))
    return daysDiff <= 30 && daysDiff >= 0
  })
  
  let daysSinceLastReaction = null
  
  if (isMockData) {
    // Return 2 days for mock data
    daysSinceLastReaction = 2
  } else {
    const lastReaction = checkins
      .slice()
      .reverse()
      .find(c => (c.breakout > 1 || c.irritation > 1 || c.dryness > 1 || c.redness > 1))
    
    if (lastReaction) {
      const lastReactionDate = new Date(lastReaction.date)
      const today = new Date()
      daysSinceLastReaction = Math.floor((today - lastReactionDate) / (1000 * 60 * 60 * 24))
    }
  }

  return {
    overallTrend,
    mostImproved,
    daysSinceLastReaction,
    totalCheckins: checkins.length
  }
}

